---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway-{{ template "tearoom.fullname" . }}
  namespace: {{ .Values.pod.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: {{ .Values.apache.port.number }}
      name: {{ .Values.apache.port.name }}
      protocol: HTTP
    hosts:
    - '*'
