---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tearoom-tearoom
spec:
  host: tearoom-tearoom.deployment.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
