---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway-tls-{{ template "tearoom.fullname" . }}
  namespace: {{ .Values.pod.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
