---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tearoom.fullname" . }}
  labels:
    app: {{ template "tearoom.fullname" . }}
    version: {{ .Values.pod.version }}
    tearoom_version: {{ .Values.tearoom.version }}
    apache_version: {{ .Values.apache.version }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{- if .Values.pod.service.annotations }}
{{ toYaml .Values.pod.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.pod.service.type }}
  ports:
  - name: {{ .Values.apache.port.name }}
    port: {{ .Values.apache.port.number }}
{{- if .Values.pod.service.nodePort }}
    nodePort: {{ .Values.pod.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "tearoom.fullname" . }}
