---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-gateway-{{ template "tearoom.fullname" . }}
  namespace: {{ .Values.pod.namespace }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: {{ .Values.apache.port.number }}
      name: {{ .Values.apache.port.name }}
      protocol: {{ .Values.apache.port.protocol }}
    hosts:
    - '*'

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "tearoom.fullname" . }}
  namespace: {{ .Values.pod.namespace }}
spec:
  hosts:
#  - '{{ template "tearoom.fullname" . }}.deployment.svc.cluster.local'
  - '*'
  gateways:
  - 'default-gateway-{{ template "tearoom.fullname" . }}'
  http:
  - match:
    - uri:
        prefix: '/tearoom'
    route:
    - destination:
        port:
          number: {{ .Values.apache.port.number }}
        host: '{{ template "tearoom.fullname" . }}.deployment.svc.cluster.local'
      weight: 100
