---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "tearoom.fullname" . }}
  namespace: {{ .Values.pod.namespace }}
spec:
  hosts:
  - {{ template "tearoom.fullname" . }}.deployment.svc.cluster.local                   # what to specify to the -HHost when using curl
  gateways:
  - default-gateway-{{ template "tearoom.fullname" . }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.apache.port.number }}
        host: {{ template "tearoom.fullname" . }}
