---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: deployment-tearoom-tearoom
  namespace: deployment
spec:
  hosts:
  - "*"
  gateways:
  - default-gateway-tearoom-tearoom
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: deployment-tearoom-tearoom
