---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "tearoom.fullname" . }}-tls
  namespace: {{ .Values.pod.namespace }}
spec:
  hosts:
  - {{ template "tearoom.fullname" . }}
  gateways:
  - default-gateway-tls-{{ template "tearoom.fullname" . }}
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /healthcheck
    route:
    - destination:
        port:
          number: {{ .Values.apache.port.number }}
        host: {{ template "tearoom.fullname" . }}
