---
#apiVersion: helm.integrations.flux.weave.works/v1alpha2
apiVersion: flux.weave.works/v1beta1
kind: FluxHelmRelease
metadata:
  name: webapp
  namespace: deployment
  labels:
    chart: webapp
  annotations:
    flux.weave.works/automated: "true"
#    flux.weave.works/tag.webapp: semver:*.*
    flux.weave.works/tag.chart-image: semver:*.*

spec:
  releaseName: webapp
  chart:
    git: ssh://git@github.com/lmctest/flux-example
    ref: master
    path: charts/webapp
  values:
    webapp:
      version: v0.2.2
      istio_inject: enabled
      replicas: 1
      image: lmctest/test:0.5
      persistence:
        enabled: false
