---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: webapp
  namespace: test-deployment
  labels:
    chart: webapp
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.webapp: glob:*.*

spec:
  chartGitPath: webapp
  values:
    replicas: 1
    image: registry.hub.docker.com/lmctest/test:0.1
    persistence:
      enabled: false
