apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "webapp.fullname" . }}
  labels:
    app: {{ template "webapp.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.webapp.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "webapp.fullname" . }}
        env: canary
        sidecar.istio.io/inject: {{ .Values.webapp.istio_inject }}
      annotations:
        sidecar.istio.io/inject: {{ .Values.webapp.istio_inject }}
    spec:
      containers:
      - name: webapp
        image: "{{ .Values.webapp.image }}"
        imagePullPolicy: {{ .Values.webapp.imagePullPolicy | quote }}
        ports:
        - name: http2
          containerPort: 5001
