---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "webapp.fullname" . }}
  labels:
    app: {{ template "webapp.fullname" . }}
    version: {{ .Values.webapp.version }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.webapp.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "webapp.fullname" . }}
        version: {{ .Values.webapp.version }}
    spec:
      containers:
      - name: webapp
        image: "{{ .Values.webapp.image }}"
        imagePullPolicy: {{ .Values.webapp.imagePullPolicy | quote }}
        ports:
          - containerPort: 5001
        volumeMounts:
          - name: istio-certs
            mountPath: /etc/istio-certs
      volumes:
      - name: istio-certs
        secret:
          secretName: istio-certs
