---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webapp-gateway
  namespace: deployment
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - webapp.architecture.lmc
    port:
      name: http
      number: 80
      protocol: HTTP
