---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "webapp.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - {{ template "webapp.fullname" . }}.architecture.lmc
    port:
      name: http
      number: 80
      protocol: HTTP
