---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "webapp.fullname" . }}
  labels:
    app: {{ template "webapp.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{- if .Values.webapp.service.annotations }}
{{ toYaml .Values.webapp.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
  - name: http-webapp
    port: 5001
{{- if .Values.webapp.service.nodePort }}
    nodePort: {{ .Values.webapp.service.nodePort }}
{{- end }}
  selector:
    app: {{ template "webapp.fullname" . }}
