---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "webapp.fullname" . }}-route
spec:
  hosts:
  - {{ template "webapp.fullname" . }}.deployment.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: "/"
  - route:
    - destination:
        host: {{ template "webapp.fullname" . }}.deployment.svc.cluster.local
        # subset: v1
    corsPolicy:
      allowOrigin:
      - lmc.eu
      allowMethods:
      - POST
      - GET
      allowCredentials: false
      allowHeaders:
      - X-Foo-Bar
      maxAge: "1d"
