---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: deployment-webapp-webapp
  namespace: deployment
spec:
  hosts:
  - "*"
  gateways:
  - default-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 5001
        host: deployment-webapp-webapp
