---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "webapp.fullname" . }}
spec:
  gateways:
  - webapp-gateway
  hosts:
  - "{{ template "webapp.fullname" . }}.architecture.lmc"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ template "webapp.fullname" . }}
        port:
          number: 5001
