---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp
  namespace: deployment
spec:
  gateways:
  - webapp-gateway
  hosts:
  - "webapp.architecture.lmc"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: 10.11.254.40
        port:
          number: 5001
