---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-tls
spec:
  hosts:
  - "webapp.example.com"
  gateways:
  - webapp-gateway-tls
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /healthcheck
    route:
    - destination:
        port:
          number: 5001
        host: deployment-webapp-webapp
