---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "webapp.fullname" . }}-tls
spec:
  hosts:
  - "{{ template "webapp.fullname" . }}.example.com"
  gateways:
  - {{ template "webapp.fullname" . }}-gateway-tls
  http:
  - match:
    - uri:
        prefix: /
    - uri:
        prefix: /healthcheck
    route:
    - destination:
        port:
          number: 5001
        host: {{ template "webapp.fullname" . }}
